### ISSUE TITLE
Workers of different sizes

### ISSUE THREAD

**Issue by JR-Rong** [zcaicaros/manager-worker-mtsptwr#1]
Hello, Thank you for implementing mtsptwr.
When I learned your code, I saw a lot of trained workers in the repo. How did you get these trained workers? Are there any implementations for related workers in other repo?
Thanks for your time!

**Comment by zcaicaros** [comment]
Thanks for your interest. I am sorry for not getting back to you sooner. The code for training the worker agent will be released soon.

**Comment by JR-Rong** [comment]
thank you!
